In [3]:
from pathlib import Path
import fuzzymatcher
import recordlinkage

In [2]:
!pip install fuzzymatcher
!pip install recordlinkage

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting fuzzymatcher
  Downloading fuzzymatcher-0.0.6-py3-none-any.whl (15 kB)
Collecting metaphone
  Downloading Metaphone-0.6.tar.gz (14 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from fuzzymatcher) (1.3.5)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from fuzzymatcher) (2.8.2)
Collecting python-Levenshtein
  Downloading python-Levenshtein-0.12.2.tar.gz (50 kB)
     |████████████████████████████████| 50 kB 2.1 MB/s
Collecting rapidfuzz
  Downloading rapidfuzz-2.1.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 9.6 MB/s
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->fuzzymatcher) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->fuzzymatcher) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil->fuzzymatcher) (1.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from python-Levenshtein->fuzzymatcher) (57.4.0)
Collecting jarowinkler<1.1.0,>=1.0.3
  Downloading jarowinkler-1.0.5-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (102 kB)
     |████████████████████████████████| 102 kB 43.6 MB/s
Building wheels for collected packages: metaphone, python-Levenshtein
  Building wheel for metaphone (setup.py) ... done
  Created wheel for metaphone: filename=Metaphone-0.6-py3-none-any.whl size=13918 sha256=c6177d70eea84a83ad62e6f87ce7cfd7a9f45dbe1cbeb144b7d1fce92fb0f172
  Stored in directory: /root/.cache/pip/wheels/1d/a8/cb/6f8902aa5457bd71344e00665c230e9c45255b3f57f2194a0f
  Building wheel for python-Levenshtein (setup.py) ... done
  Created wheel for python-Levenshtein: filename=python_Levenshtein-0.12.2-cp37-cp37m-linux_x86_64.whl size=149878 sha256=a6dc99d9db2085e872ffd692d6cc2b3b13c2d0488b9bd4830cf66b574139e301
  Stored in directory: /root/.cache/pip/wheels/05/5f/ca/7c4367734892581bb5ff896f15027a932c551080b2abd3e00d
Successfully built metaphone python-Levenshtein
Installing collected packages: jarowinkler, rapidfuzz, python-Levenshtein, metaphone, fuzzymatcher
Successfully installed fuzzymatcher-0.0.6 jarowinkler-1.0.5 metaphone-0.6 python-Levenshtein-0.12.2 rapidfuzz-2.1.1
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting recordlinkage
  Downloading recordlinkage-0.15-py3-none-any.whl (926 kB)
     |████████████████████████████████| 926 kB 5.2 MB/s
Requirement already satisfied: scipy>=1 in /usr/local/lib/python3.7/dist-packages (from recordlinkage) (1.4.1)
Requirement already satisfied: pandas<2,>=1 in /usr/local/lib/python3.7/dist-packages (from recordlinkage) (1.3.5)
Requirement already satisfied: numpy>=1.13.0 in /usr/local/lib/python3.7/dist-packages (from recordlinkage) (1.21.6)
Collecting jellyfish>=0.8.0
  Downloading jellyfish-0.9.0.tar.gz (132 kB)
     |████████████████████████████████| 132 kB 48.2 MB/s
Requirement already satisfied: scikit-learn>=0.19.0 in /usr/local/lib/python3.7/dist-packages (from recordlinkage) (1.0.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from recordlinkage) (1.1.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas<2,>=1->recordlinkage) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas<2,>=1->recordlinkage) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas<2,>=1->recordlinkage) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.19.0->recordlinkage) (3.1.0)
Building wheels for collected packages: jellyfish
  Building wheel for jellyfish (setup.py) ... done
  Created wheel for jellyfish: filename=jellyfish-0.9.0-cp37-cp37m-linux_x86_64.whl size=73985 sha256=37c7a850bdd87c1914d092ab20195ed82ee194780efff6f0c98692615b09df22
  Stored in directory: /root/.cache/pip/wheels/fe/99/4e/646ce766df0d070b0ef04db27aa11543e2767fda3075aec31b
Successfully built jellyfish
Installing collected packages: jellyfish, recordlinkage
Successfully installed jellyfish-0.9.0 recordlinkage-0.15

In [7]:
# Deduping follows the same process, you just use 1 single dataframe
dupe_indexer = recordlinkage.Index()
dupe_indexer.sortedneighbourhood(left_on='State')
dupe_candidate_links = dupe_indexer.index(hospital_dupes)

In [8]:
# Comparison step
compare_dupes = recordlinkage.Compare()
compare_dupes.string('City', 'City', threshold=0.85, label='City')
compare_dupes.string('Phone Number',
                     'Phone Number',
                     threshold=0.85,
                     label='Phone_Num')
compare_dupes.string('Facility Name',
                     'Facility Name',
                     threshold=0.80,
                     label='Hosp_Name')
compare_dupes.string('Address',
                     'Address',
                     threshold=0.85,
                     label='Hosp_Address')
dupe_features = compare_dupes.compute(dupe_candidate_links, hospital_dupes)

In [10]:
dupe_features

                             City  Phone_Num  Hosp_Name  Hosp_Address
Account_Num_1 Account_Num_2
26270         28485           0.0        0.0        0.0           0.0
              30430           0.0        0.0        0.0           0.0
              43602           0.0        0.0        0.0           0.0
59585         28485           0.0        0.0        0.0           0.0
              30430           0.0        0.0        0.0           0.0
...                           ...        ...        ...           ...
64029         38600           0.0        0.0        0.0           0.0
              35413           0.0        0.0        0.0           0.0
              81525           0.0        0.0        0.0           0.0
              82916           0.0        0.0        0.0           0.0
              18907           0.0        0.0        0.0           0.0

[981277 rows x 4 columns]

In [11]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [16]:
df = pd.read_csv('/content/gdrive/MyDrive/Python/schema_matching_data.csv').reset_index().drop(columns=['Unnamed: 0'])
df

,index,author_name,cover_type,image_url,name,num_page,price,provider,publisher,release_year,size,url
0,0,Fuji,Mềm,https://newshop.vn/public/uploads/products/485...,Sách Tương Phản - Đồ Dùng Của Bé,20,60000,Nhà Sách AZ Việt Nam,Thế Giới,2022,150x150,https://newshop.vn/sach-tuong-phan-do-dung-cua...
1,1,Fuji,Cứng,https://newshop.vn/public/uploads/products/485...,Combo Sách Tương Phản (Bộ 4 Cuốn),20,240000,Nhà Sách AZ Việt Nam,Thế Giới,2022,150x150,https://newshop.vn/combo-sach-tuong-phan-bo-4-...
2,2,Mèo Vũ Trụ,Mềm,https://newshop.vn/public/uploads/products/485...,Chạm - Hành Trình Cảm Xúc Của 12 Chòm Sao,184,99000,Nhà Sách AZ Việt Nam,Thế Giới,2022,130x180,https://newshop.vn/cham-hanh-trinh-cam-xuc-cua...
3,3,Manh A Công Tử,Mềm,https://newshop.vn/public/uploads/products/485...,Môn Đồ - Sư Phụ Giả - Tập 7,224,129000,Nhà Sách AZ Việt Nam,Thế Giới,2022,145x205,https://newshop.vn/mon-do-su-phu-gia-tap-7.htm...
4,4,Motoro Mase,Mềm,https://newshop.vn/public/uploads/products/485...,Ikigami - Tuyển Tập Những Câu Chuyện Lay Động ...,216,45000,NXB Trẻ,Trẻ,2022,130x10,https://newshop.vn/ikigami-tuyen-tap-nhung-cau...
...,...,...,...,...,...,...,...,...,...,...,...,...
48929,48929,HT Thích Minh Thiền,Bìa mềm,No image,Tham thiền,302,189.000,Thái Hà Books,Tiếp tục,2020.0,(cm),https://book365.vn/sach/411073_tham-thien.html
48930,48930,TS. Đặng Thị Việt Đức,Bìa mềm,No image,Quản trị tri thức trong Doanh nghiệp - Thời hạ...,302,11962.5,NXB Thông tin và Truyền thông,Thông tin và Truyền thông,2017.0,(cm),https://book365.vn/sach/416559_quan-tri-tri-th...
48931,48931,Phòng Thương mại quốc tế ICC,Bìa mềm,No image,Bộ tập quán quốc tế về L/C - Các văn bản có hi...,302,9570,NXB Thông tin và Truyền thông,Thông tin và Truyền thông,2016.0,(cm),https://book365.vn/sach/416593_bo-tap-quan-quo...
48932,48932,Lê Thị Thu Hà,Bìa mềm,No image,Bảo hộ chỉ dẫn địa lý của Việt Nam trong điều ...,302,18183,NXB Thông tin và Truyền thông,Thông tin và Truyền thông,2017.0,(cm),https://book365.vn/sach/416497_bao-ho-chi-dan-...
48933,48933,TS. Đặng Thị Việt Đức,Bìa mềm,No image,Lý thuyết tài chính tiền tệ - Thời hạn: 12 tháng,302,16747.5,NXB Thông tin và Truyền thông,Thông tin và Truyền thông,2017.0,(cm),https://book365.vn/sach/416413_ly-thuyet-tai-c...

In [21]:
dupe_indexer = recordlinkage.Index()
dupe_indexer.sortedneighbourhood(left_on='num_page')
dupe_candidate_links = dupe_indexer.index(df)

In [125]:
compare_dupes = recordlinkage.Compare()
compare_dupes.string('name', 'name', threshold=0.9, label='Name')
compare_dupes.string('author_name',
                     'author_name',
                     threshold=0.8,
                     label='Author_name')
compare_dupes.string('price',
                     'price',
                     threshold=0.7,
                     label='Price')
compare_dupes.string('release_year',
                     'release_year',
                     threshold=0.7,
                     label='Release_year')
dupe_features = compare_dupes.compute(dupe_candidate_links, df)

In [126]:
dupe_features

             Name  Author_name  Price  Release_year
20016 17461   0.0          0.0    0.0           0.0
20017 17461   0.0          0.0    0.0           0.0
20031 17461   0.0          0.0    0.0           0.0
20035 17461   0.0          0.0    0.0           0.0
20364 17461   0.0          0.0    0.0           0.0
...           ...          ...    ...           ...
48449 9992    0.0          0.0    0.0           0.0
      20696   0.0          0.0    0.0           0.0
      20733   0.0          0.0    0.0           0.0
      23376   0.0          0.0    0.0           0.0
48692 10997   0.0          0.0    0.0           0.0

[8386421 rows x 4 columns]

In [127]:
dupe_features.sum(axis=1).value_counts().sort_index(ascending=False)

4.0      10367
3.0      30412
2.0     341971
1.0    2381305
0.0    5622366
dtype: int64

In [128]:
potential_dupes = dupe_features[dupe_features.sum(axis=1) > 2].reset_index()
potential_dupes['Name_0'] = potential_dupes['Name'].apply(lambda x: x*2)
potential_dupes['Author_name_0'] = potential_dupes['Author_name'].apply(lambda x: x*1)
potential_dupes['Price_0'] = potential_dupes['Price'].apply(lambda x: x*0.5)
potential_dupes['Release_year_0'] = potential_dupes['Release_year'].apply(lambda x: x*0.5)

potential_dupes['Score'] = potential_dupes.loc[:, 'Name_0':'Release_year_0'].sum(axis=1)/4
potential_dupes = potential_dupes.drop(columns=['Name_0', 'Author_name_0', 'Price_0', 'Release_year_0'])
potential_dupes = potential_dupes[potential_dupes['Score']  > 0.6]

In [129]:
potential_dupes.sort_values(by=['Score'], ascending=False)

       level_0  level_1  Name  Author_name  Price  Release_year  Score
40769    14604    14601   1.0          1.0    1.0           1.0   1.00
36922    22217    22214   1.0          1.0    1.0           1.0   1.00
24421    40354    40270   1.0          1.0    1.0           1.0   1.00
36929    42930    22143   1.0          1.0    1.0           1.0   1.00
36928    42620    22217   1.0          1.0    1.0           1.0   1.00
...        ...      ...   ...          ...    ...           ...    ...
24732    40674    40491   1.0          0.0    1.0           1.0   0.75
24731    40674    40480   1.0          0.0    1.0           1.0   0.75
24730    40674    40458   1.0          0.0    1.0           1.0   0.75
24729    40674    40365   1.0          0.0    1.0           1.0   0.75
22979    35589    35583   1.0          0.0    1.0           1.0   0.75

[16621 rows x 7 columns]

In [130]:
df[df.index.isin([22217, 22214])]

,index,author_name,cover_type,image_url,name,num_page,price,provider,publisher,release_year,size,url
22214,22214,Maru Nagao,Mềm,https://newshop.vn/public/uploads/products/294...,Họa Sư Ma Mèo - Tập 2,230,28000,Nhà Xuất Bản Kim Đồng,Kim Đồng,2020,176x113,https://newshop.vn/hoa-su-ma-meo-tap-2.html?ca...
22217,22217,Maru Nagao,Mềm,https://newshop.vn/public/uploads/products/294...,Họa Sư Ma Mèo - Tập 3,230,28000,Nhà Xuất Bản Kim Đồng,Kim Đồng,2020,176x113,https://newshop.vn/hoa-su-ma-meo-tap-3.html?ca...

In [37]:
potential_dupes

       level_0  level_1  Name  Author_name  Price  Release_year  Score
0        26958     2328   0.0          1.0    1.0           1.0    3.0
1        29269    25076   0.0          1.0    1.0           1.0    3.0
2        34254    25077   0.0          1.0    1.0           1.0    3.0
3        45456     2328   0.0          1.0    1.0           1.0    3.0
4        17049    16874   1.0          0.0    1.0           1.0    3.0
...        ...      ...   ...          ...    ...           ...    ...
60975    48373    47035   0.0          1.0    1.0           1.0    3.0
60976    20900    19550   0.0          1.0    1.0           1.0    3.0
60977    45092    23602   1.0          1.0    1.0           1.0    4.0
60978    22489     2533   0.0          1.0    1.0           1.0    3.0
60979    39012     5466   0.0          1.0    1.0           1.0    3.0

[60980 rows x 7 columns]

In [42]:
potential_dupes.loc[potential_dupes['level_0'] ]

26958    Tiếng Gọi Nơi Hoang Dã (Khang Việt)
Name: name, dtype: object

In [45]:
len(set(potential_dupes['level_0']))

11768

In [158]:
df.iloc[[45092, 23602]]

,index,author_name,cover_type,image_url,name,num_page,price,provider,publisher,release_year,size,url
45092,45092,Joel Dicker,Bìa mềm,No image,Sự thật vụ mất tích nữ nhà báo Stephanie Mailer,812,249.000,Nhà xuất bản Phụ nữ Việt Nam,Phụ nữ,2020.0,(cm),https://book365.vn/sach/429088_su-that-vu-mat-...
23602,23602,Joel Dicker,Mềm,https://newshop.vn/public/uploads/products/282...,Sự Thật Vụ Mất Tích Nữ Nhà Báo Stephanie Mailer,810,249000,Nhà Xuất Bản Phụ Nữ,Phụ Nữ Việt Nam,2020,155x235,https://newshop.vn/su-that-vu-mat-tich-nu-nha-...

In [149]:
df_1 = df.copy()
arr_drop = []

In [173]:
df_1 = df.copy()
arr_drop = []
for i in list(set(potential_dupes['level_0'])):
  name_1 = df.iloc[[i]]['name']
  arr = potential_dupes.loc[potential_dupes['level_0'] ==  i]['level_1'].to_list()
  #print(arr)
  for j in arr:
    name_2 = df.iloc[[j]]['name']
    if diff(str(name_1), str(name_2)) == True:
      continue
    arr_drop.append(j)

In [177]:
len(list(set(arr_drop)))

3920

In [186]:
df_1 = df.copy()
df_1 = df_1.drop(list(set(arr_drop)))
df_1 = df_1.drop(columns=['index'])
#df_1 = df_1.reset_index()
df_1.to_csv('data')

In [172]:
arr_diff = []
for i in list(set(potential_dupes['level_0'])):
  print(i)
  name_1 = df.iloc[[i]]['name']
  arr = potential_dupes.loc[potential_dupes['level_0'] ==  i]['level_1'].to_list()
  print(arr)
  for j in arr:
    name_2 = df.iloc[[j]]['name']
    if diff(str(name_1), str(name_2)) == True:
      arr_diff.append(j)

len(list(set(arr_diff)))

40962
[40863]
40966
[40393, 40625]
40967
[40943]
40968
[40880, 40945]
32778
[25206]
40973
[40154, 40398, 40443, 40473, 40481, 40739]
40976
[40126, 40478, 40587]
40977
[40880, 40945, 40968]
8210
[8208]
8211
[8208, 8210]
40983
[40220, 40242, 40360, 40417, 40805]
8217
[8208, 8210, 8211]
40986
[40951]
40985
[40485, 40723]
40988
[40928]
24608
[24606]
32801
[257]
40997
[40615]
41001
[26758]
42
[37]
41005
[40928, 40988]
16430
[15006]
41006
[40589]
41009
[40655, 40660, 40701, 40817, 40860, 40905]
41010
[40926]
41013
[40659]
41017
[40034, 40608]
24633
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522, 16523, 16524, 16525, 16527, 16528, 16530, 16532, 16533, 16618, 16620, 16621, 20600, 20796, 20986, 23177, 23178, 23179, 23180]
24634
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522, 16523, 16524, 16525, 16527, 16528, 16530, 16532, 16533, 16618, 16620, 16621, 20600, 20796, 20986, 23177, 23178, 23179, 23180, 24633]
24636
[16563, 16565, 16571]
41018
[40801]
24638
[16563, 16565, 16571, 24636]
41020
[40285, 40623, 40712]
41024
[40941]
41026
[40954]
32836
[13409]
8266
[8264]
41035
[40575]
41034
[40961]
41038
[40877]
41039
[40934]
8276
[8273]
8277
[8273, 8276]
24661
[24660]
41047
[39825, 40048, 40109, 40124, 40247, 40266, 40270, 40300, 40307, 40308, 40312, 40354, 40365, 40458, 40480, 40491, 40499, 40533, 40536, 40547, 40580, 40598, 40674, 40679, 40696, 40719, 40720, 40722, 40736, 40759, 40766, 40774, 40785, 40823, 40900]
41049
[40776]
8285
[8281]
24670
[24669]
8287
[8274]
8288
[8281, 8285]
8289
[8274, 8287]
8290
[8281, 8285, 8288]
8291
[8273, 8276, 8277]
41057
[39825, 40048, 40109, 40124, 40247, 40266, 40270, 40300, 40307, 40308, 40312, 40354, 40365, 40458, 40480, 40491, 40499, 40533, 40536, 40547, 40580, 40598, 40674, 40679, 40696, 40719, 40720, 40722, 40736, 40759, 40766, 40774, 40785, 40823, 40900, 41047]
8293
[8265, 8273, 8274, 8276, 8277, 8287, 8289, 8291]
24677
[15058]
41063
[40337, 40479, 40668, 40772]
41056
[41033]
8301
[8296]
8303
[8296, 8301]
8304
[8296, 8301, 8303]
8305
[8296, 8301, 8303, 8304]
8307
[8296, 8301, 8303, 8304, 8305]
41078
[41077]
41079
[40299, 40306, 40427, 40447, 40612, 40637, 40639, 40788, 40845]
8313
[6963]
41082
[40347, 40638]
41084
[40655, 40660, 40701, 40817, 40860, 40905, 41009]
24705
[22194, 22196]
41089
[26947, 27062, 27355, 39545, 39908, 40135]
16515
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358]
16516
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515]
8324
[8296, 8301, 8303, 8304, 8305, 8307]
41092
[40880, 40945, 40968, 40977]
16519
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516]
16520
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519]
16521
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520]
16522
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521]
16523
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522]
16524
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522, 16523]
16525
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6625, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522, 16523, 16524]
41100
[40583, 40628, 40808, 40876, 40952, 40958, 40959]
16527
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522, 16523, 16524, 16525]
16528
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522, 16523, 16524, 16525, 16527]
41105
[40607]
16530
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522, 16523, 16524, 16525, 16527, 16528]
24721
[12672, 13070, 13290, 22134]
16532
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522, 16523, 16524, 16525, 16527, 16528, 16530]
16533
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522, 16523, 16524, 16525, 16527, 16528, 16530, 16532]
24720
[24719]
41106
[40800]
41107
[40800, 41106]
24730
[24729]
41116
[39825, 40048, 40109, 40124, 40247, 40266, 40270, 40300, 40307, 40308, 40312, 40354, 40365, 40458, 40480, 40491, 40499, 40533, 40536, 40547, 40580, 40598, 40674, 40679, 40696, 40719, 40720, 40722, 40736, 40759, 40766, 40774, 40785, 40823, 40900, 41047, 41057]
41117
[27269, 27440, 27452, 39605, 39616, 39698, 40163, 40190, 40250, 40388, 40585, 40706, 40729, 40741, 40948]
41118
[40589, 41006]
41119
[40979]
41121
[40565]
8360
[7065, 7506]
41132
[41039]
41134
[41040]
16565
[16563]
41142
[40154, 40398, 40443, 40473, 40481, 40739, 40973]
41141
[39825, 40048, 40109, 40124, 40247, 40266, 40270, 40300, 40307, 40308, 40312, 40354, 40365, 40458, 40480, 40491, 40499, 40533, 40536, 40547, 40580, 40598, 40674, 40679, 40696, 40719, 40720, 40722, 40736, 40759, 40766, 40774, 40785, 40823, 40900, 41047, 41057, 41116]
24758
[22263, 22264, 22265, 22387, 22423, 22428, 22906, 22964]
41145
[41114]
41146
[40256, 40615, 40841]
16571
[16563, 16565]
24764
[10221]
41149
[39825, 40048, 40109, 40124, 40247, 40266, 40270, 40300, 40307, 40308, 40312, 40354, 40365, 40458, 40480, 40491, 40499, 40533, 40536, 40547, 40580, 40598, 40674, 40679, 40696, 40719, 40720, 40722, 40736, 40759, 40766, 40774, 40785, 40823, 40900, 41047, 41057, 41116, 41141]
32957
[13535]
41151
[11490, 11599, 11614, 11666, 26292]
24767
[22299, 22324, 22329, 22330]
41155
[23903]
41156
[15230]
24773
[22263, 22264, 22265, 22387, 22423, 22428, 22906, 22964, 24758]
16587
[16586]
16588
[16586, 16587]
24781
[22901]
41166
[3167, 3588, 11635, 13187, 22033, 22141]
41168
[39490, 39580, 39643, 39855, 39857, 40014, 40021, 40027, 40050, 40098]
32979
[11503]
41172
[39490, 39580, 39643, 39855, 39857, 40014, 40021, 40027, 40050, 40098, 41168]
41174
[21983]
24796
[8114, 8115, 8116, 8126]
8417
[8413]
41186
[1905, 1959, 21940, 21949, 21999, 22004, 22025, 24900]
8419
[8415]
41188
[39853, 39937, 40015, 40051, 40052, 40275, 40489, 40734]
8420
[8415, 8419]
41191
[41177]
8424
[8415, 8419, 8420]
233
[4]
16618
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6625, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522, 16523, 16524, 16525, 16527, 16528, 16530, 16532, 16533]
41194
[39675]
16620
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6625, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522, 16523, 16524, 16525, 16527, 16528, 16530, 16532, 16533, 16618]
16621
[6539, 6556, 6560, 6561, 6562, 6619, 6620, 6621, 6622, 6623, 6624, 6626, 6627, 6631, 6633, 6684, 7358, 16515, 16516, 16519, 16520, 16521, 16522, 16523, 16524, 16525, 16527, 16528, 16530, 16532, 16533, 16618, 16620]
41197
[39490, 39580, 39643, 39855, 39857, 40014, 40021, 40027, 40050, 40098, 41172, 41168]
8423
[8414]
41200
[22023]
41201
[41165]
41205
[3505, 12712]
41207
[21953]
41209
[41165, 41201]
41211
[41202]
33021
[3836]
41216
[41215]
41217
[41215, 41216]
41218
[41198]
16641
[16640]
24833
[24832]
41224
[1905, 1959, 21940, 21949, 21999, 22004, 22025, 24900, 41186]
41229
[447, 908, 1315, 2625, 4505, 11474, 11756, 11799, 11923]
41231
[678, 805, 877, 1088, 1550, 1710, 1822, 3839, 3926, 11782, 11795, 11796, 11832, 12227, 12348, 12521, 12711, 13393, 13741, 24142]
41232
[41176]
41234
[354, 657, 497]
41235
[21918]
41236
[41177, 41191]
24852
[22829, 22830, 22831]
24854
[22829, 22830, 22831, 24852]
41241
[41177, 41191, 41236]
41243
[832, 21959, 21974, 27010]
41248
[832, 21959, 21974, 41243]
41249
[41193]
24871
[22730, 22731, 22736, 22737, 22749]
41257
[678, 805, 877, 1088, 1550, 1710, 1822, 3839, 3926, 11782, 11795, 11796, 11832, 12227, 12348, 12521, 12711, 13393, 13741, 24142, 41231]
24874
[22797]
24875
[12288, 12374]
41259
[39853, 39937, 40015, 40051, 40052, 40275, 40489, 40734, 41188]
41261
[41195]
41264
[41255]
41265
[39853, 39937, 40015, 40051, 40052, 40275, 40489, 40734, 41188, 41259]
41267
[40244]
41269
[11354, 11454, 11522, 11679, 30889]
41274
[39825, 40536, 40547, 40696, 40719, 40720, 40722, 40759, 40766, 40774]
41277
[39675, 41194]
41283
[39680, 41161]
24900
[1905, 1959, 21940, 21949, 21999, 22004, 22025]
41285
[14223]
41292
[447, 908, 1315, 2625, 4272, 11474, 11756, 11799, 11923, 41229]
41293
[41287]
41296
[11330]
41297
[25939]
41302
[39716]
41304
[41177, 41191, 41236, 41241]
41305
[41177, 41191, 41236, 41241, 41304]
41309
[39675, 41194, 41277]
41311
[39788, 39852, 39854, 41244]
41312
[41177, 41191, 41236, 41241, 41304, 41305]
41314
[40421]
16738
[16732]
41316
[39675, 41194, 41277, 41309]
41317
[41177, 41191, 41236, 41241, 41304, 41305, 41312]
16742
[6829, 6834, 6835]
8551
[7608]
41319
[21993]
41321
[41176, 41232]
41324
[21958, 21968, 21990, 21994, 21997, 22021, 22031]
41327
[39675, 41194, 41277, 41309, 41316]
41328
[39853, 39937, 40015, 40051, 40052, 40275, 40489, 40734, 41188, 41259, 41265]
41329
[39675, 41194, 41277, 41309, 41316, 41327]
41330
[39675, 41194, 41277, 41309, 41316, 41327, 41329]
41332
[40053]
41333
[4145]
41338
[39853, 39937, 40015, 40051, 40052, 40275, 40489, 40734, 41188, 41259, 41265, 41328]
41339
[41193, 41249]
41340
[41193, 41249, 41339]
41342
[41193, 41249, 41339, 41340]
41343
[39675, 41194, 41277, 41309, 41316, 41327, 41329, 41330]
41345
[13394]
41347
[447, 908, 1315, 2625, 3417, 11474, 11756, 11799, 11923, 41229, 41292]
41350
[832, 21959, 21974, 39791, 41243, 41248]
41351
[23697]
41353
[18316, 18319, 18323, 18324, 18325, 18326, 18327, 18328, 18329, 21077, 25275, 8282]
41355
[41239]
24971
[17484, 17931, 18023]
41357
[41239, 41355]
41358
[1055, 1447]
24974
[24972]
41360
[41165, 41209, 41201]
41365
[39853, 39937, 40015, 40051, 40052, 40275, 40489, 40734, 41188, 41259, 41265, 41328, 41338]
24982
[24981]
41367
[41254]
16793
[16790]
41371
[41193, 41249, 41339, 41340, 41342]
8603
[8519]
41372
[678, 805, 877, 1088, 1550, 1710, 1822, 3839, 3926, 11782, 11795, 11796, 11832, 12227, 12348, 12521, 12711, 13393, 13741, 24142, 41231, 41257]
414
[410]
415
[392]
41376
[41370]
41375
[11286]
41378
[11572, 11621]
41379
[21918, 41235]
24998
[17250]
41383
[41192]
41384
[11349, 11422, 11586, 11660, 21944, 21960]
41386
[39825, 40536, 40547, 40696, 40719, 40720, 40722, 40759, 40766, 40774, 41274]
41387
[450, 556]
41388
[39853, 39937, 40015, 40051, 40052, 40275, 40489, 40734, 41188, 41259, 41265, 41328, 41338, 41365]
41389
[41225]
41390
[39675, 41194, 41277, 41309, 41316, 41327, 41329, 41330, 41343]
41391
[41161, 41283]
33205
[33179]
41397
[1905, 1959, 21940, 21949, 21999, 22004, 22025, 24900, 41186, 41224]
25013
[16967]
41400
[3578]
41398
[41279]
41403
[41289]
41405
[39825, 40536, 40547, 40696, 40719, 40720, 40722, 40759, 40766, 40774, 41274, 41386]
41407
[41401]
41408
[40053, 41332]
41409
[18503]
41412
[21952]
453
[197]
41414
[41161, 41283, 41391]
41416
[41177, 41191, 41236, 41241, 41304, 41305, 41312, 41317]
25037
[17484, 17931, 18023, 24971]
33230
[2584]
16847
[5392, 5397, 5399, 15294, 15295, 15301, 15322, 15324, 15327, 14609, 15059]
41424
[1055, 1447, 41358]
41423
[41177, 41191, 41236, 41241, 41304, 41305, 41312, 41317, 41416]
25042
[3782, 13003, 13282, 13284, 13287, 13288, 15170, 15512, 15963, 16277, 16279, 16281, 17049, 17248, 17518, 21527]
41426
[41165, 41209, 41360, 41201]
16850
[16593]
41429
[41326]
41430
[41370, 41376]
41431
[41180]
41432
[41180, 41431]
41434
[39490, 39580, 39643, 39855, 39857, 40014, 40021, 40027, 40050, 40098, 41172, 41197, 41168]
8667
[8080]
41436
[41177, 41191, 41236, 41241, 41304, 41305, 41312, 41317, 41416, 41423]
41437
[41279, 41398]
41439
[39594, 39641]
41440
[39675, 41194, 41277, 41309, 41316, 41327, 41329, 41330, 41343, 41390]
41441
[41202, 41211]
41444
[30795]
41447
[39825, 40536, 40547, 40696, 40719, 40720, 40722, 40759, 40766, 40774, 41274, 41386, 41405]
16873
[16872]
16874
[15512]
41452
[11631]
41453
[11354, 11454, 11522, 11679, 30889, 41269]
16876
[7022]
25071
[16134, 16159, 16165, 17348, 17548, 17712, 21571, 23364]
41456
[9406]
497
[354]
41460
[39853, 39937, 40015, 40051, 40052, 40275, 40489, 40734, 41188, 41259, 41265, 41328, 41338, 41365, 41388]
41461
[39853, 39937, 40015, 40051, 40052, 40275, 40489, 40734, 41188, 41259, 41265, 41328, 41338, 41365, 41388, 41460]
33268
[27867]
41463
[41202, 41211, 41441]
41462
[39825, 40536, 40547, 40696, 40719, 40720, 40722, 40759, 40766, 40774, 41274, 41386, 41405, 41447]
41465
[39675, 41194, 41277, 41309, 41316, 41327, 41329, 41330, 41343, 41390, 41440]
41469
[41219]
41470
[14568]
41471
[41406]
41475
[41363]
25093
[7632, 17437]
41478
[39680, 41161, 41283, 41391, 41414]
41479
[39961]
41477
[4029]
41482
[41177, 41191, 41236, 41241, 41304, 41305, 41312, 41317, 41416, 41423, 41436]
25098
[17484, 17931, 18023, 18978, 24971, 25037]
41484
[41193, 41249, 41339, 41340, 41342, 41371]
41485
[39675, 41194, 41277, 41309, 41316, 41327, 41329, 41330, 41343, 41390, 41440, 41465]
524
[430]
41487
[41193, 41249, 41339, 41340, 41342, 41371, 41484]
41488
[41177, 41191, 41236, 41241, 41304, 41305, 41312, 41317, 41416, 41423, 41436, 41482]
16911
[16910]
41490
[1905, 1959, 21940, 21949, 21999, 22004, 22025, 24900, 41186, 41224, 41397]
25100
[17551, 17569]
25108
[25106]
41493
[41244, 41311]
41494
[39675, 41194, 41277, 41309, 41316, 41327, 41329, 41330, 41343, 41390, 41440, 41465, 41485]
41495
[41177, 41191, 41236, 41241, 41304, 41305, 41312, 41317, 41416, 41423, 41436, 41482, 41488]
41497
[41242]
41500
[41254, 41367]
41501
[41370, 41376, 41430]
41502
[39490, 39580, 39643, 39855, 39857, 40014, 40021, 40027, 40050, 40098, 41172, 41197, 41434, 41168]
25118
[16134, 16159, 16165, 17348, 17548, 17712, 21571, 23364, 25071]
41504
[11354, 11454, 11522, 11679, 30889, 41269, 41453]
545
[544]
41505
[21983, 41174]
16930
[7108]
41508
[41193, 41249, 41339, 41340, 41342, 41371, 41484, 41487]
41509
[41315]
41511
[41176, 41232, 41321]
41514
[41193, 41249, 41339, 41340, 41342, 41371, 41484, 41487, 41508]
41515
[39825, 40536, 40547, 40696, 40719, 40720, 40722, 40759, 40766, 40774, 41274, 41386, 41405, 41447, 41462]
41516
[41202, 41211, 41441, 41463]
556
[450]
41518
[39675, 41194, 41277, 41309, 41316, 41327, 41329, 41330, 41343, 41390, 41440, 41465, 41485, 41494]
16946
[16945]
41524
[39853, 39937, 40015, 40051, 40052, 40275, 40489, 40734, 41188, 41259, 41265, 41328, 41338, 41365, 41388, 41460, 41461]
41527
[41206]
41528
[678, 805, 877, 1088, 1550, 1710, 1822, 3839, 3926, 11782, 11795, 11796, 11832, 12227, 12348, 12521, 12711, 13393, 13741, 24142, 41231, 41257, 41372]
41531
[11490, 11599, 11614, 11666, 41151]
41532
[39680, 41161, 41283, 41391, 41414, 41478]
41534
[11613]
41536
[1905, 1959, 21940, 21949, 21999, 22004, 22025, 24900, 41186, 41224, 41397, 41490]
578
[577]
579
[576]
41541
[41161, 41283, 41391, 41414, 41478, 41532]
41543
[22003]
41548
[41173]
41549
[40438]
41551
[41177, 41191, 41236, 41241, 41304, 41305, 41312, 41317, 41416, 41423, 41436, 41482, 41488, 41495]
41552
[40531]
41553
[11469, 22009]
41554
[39490, 39580, 39643, 39855, 39857, 40014, 40021, 40027, 40050, 40098, 41172, 41197, 41434, 41502, 41168]
41555
[41177, 41191, 41236, 41241, 41304, 41305, 41312, 41317, 41416, 41423, 41436, 41482, 41488, 41495, 41551]
41556
[41177, 41191, 41236, 41241, 41304, 41305, 41312, 41317, 41416, 41423, 41436, 41482, 41488, 41495, 41551, 41555]
25173
[16874, 3782, 13003, 13282, 13284, 13287, 13288, 15170, 15512, 15963, 16277, 16279, 16281, 17049, 17248, 17518, 21527, 25042]
25170
[7928, 17783]
598
[586]
41560
[678, 805, 877, 1088, 1550, 1710, 1822, 3839, 3926, 11782, 11795, 11796, 11832, 12227, 12348, 12521, 12711, 13393, 13741, 24142, 41231, 41257, 41372, 41528]
41561
[41187]
41562
[11330, 41296]
41563
[39853, 39937, 40015, 40051, 40052, 40275, 40489, 40734, 41188, 41259, 41265, 41328, 41338, 41365, 41388, 41460, 41461, 41524]
41565
[39675, 41194, 41277, 41309, 41316, 41327, 41329, 41330, 41343, 41390, 41440, 41465, 41485, 41494, 41518]
25184
[17783, 25170]
41570
[39675, 41194, 41277, 41309, 41316, 41327, 41329, 41330, 41343, 41390, 41440, 41465, 41485, 41494, 41518, 41565]
41571
[39825, 40536, 40547, 40696, 40719, 40720, 40722, 40759, 40766, 40774, 41274, 41386, 41405, 41447, 41462, 41515]
41572
[13068, 13881, 14136, 14137, 24037, 24044]
41573
[5066]
41574
[41268]
8809
[8253]
17002
[7239, 7753]
33385
[32976]
17004
[7753, 17002]
41581
[40053, 41332, 41408]
41582
[39853, 39937, 40015, 40051, 40052, 40275, 40489, 40734, 41188, 41259, 41265, 41328, 41338, 41365, 41388, 41460, 41461, 41524, 41563]
17006
[7239, 7753, 17002]
41580
[41523]
41584
[24891]
41588
[12673]
41592
[41219, 41469]
41594
[1905, 1959, 21940, 21949, 21999, 22004, 22025, 24900, 41186, 41224, 41397, 41490, 41536]
41595
[39680, 41161, 41283, 41391, 41414, 41478, 41532, 41541]
41598
[1016, 1031, 1034, 1049, 1051, 1053, 1056, 1061, 1063, 1064, 1065, 1068, 1072, 1073, 1074, 1076, 1077, 1078, 1079, 1083, 1198]
41600
[7736]
41601
[7159]
17024
[17022]
41603
[678, 805, 877, 1088, 1550, 1710, 1822, 3839, 3926, 11782, 11795, 11796, 11832, 12227, 12348, 12521, 12711, 13393, 13741, 24142, 41231, 41257, 41372, 41528, 41560]
25219
[17860, 17923, 17926, 18823, 18836]
41605
[40528]
41606
[22059]
41608
[40833]
41610
[41165, 41209, 41360, 41426, 41201]
41611
[41422]
41616
[41177, 41191, 41236, 41241, 41304, 41305, 41312, 41317, 41416, 41423, 41436, 41482, 41488, 41495, 41551, 41555, 41556]

KeyboardInterrupt: ignored

In [155]:
len(list(set(arr_drop)))

3920

In [92]:
df.iloc[[42272]]

,index,author_name,cover_type,image_url,name,num_page,price,provider,publisher,release_year,size,url
42272,42272,Fujiko F Fujio,Bìa Mềm,https://cdn0.fahasa.com/media/catalog/product/...,Doraemon - Chú Mèo Máy Đến Từ Tương Lai Tập 33...,192,18000.0,Action,NXB Kim Đồng,2019,11.3 x 17.6,https://www.fahasa.com/doraemon-chu-meo-may-de...

In [1]:
def diff(string1, string2):
    for i in range(len(string1)):
        if (string1[i] != string2[i]) & (string1[i].isnumeric()):
            return False
    return True


print(diff("Bên Dưới Cây Cầu Arakawa - Arakawa Under The Bridge - Tập 13 - Tặng Kèm Postcard", "Bên Dưới Cây Cầu Arakawa - Arakawa Under The Bridge - Tập 14 - Tặng Kèm Postcard")) #3

False

In [189]:
df___ = pd.read_csv('/content/data').drop(columns =['Unnamed: 0'])
df___.to_csv('data.csv')

In [190]:
df___

,author_name,cover_type,image_url,name,num_page,price,provider,publisher,release_year,size,url
0,Fuji,Mềm,https://newshop.vn/public/uploads/products/485...,Sách Tương Phản - Đồ Dùng Của Bé,20,60000,Nhà Sách AZ Việt Nam,Thế Giới,2022,150x150,https://newshop.vn/sach-tuong-phan-do-dung-cua...
1,Fuji,Cứng,https://newshop.vn/public/uploads/products/485...,Combo Sách Tương Phản (Bộ 4 Cuốn),20,240000,Nhà Sách AZ Việt Nam,Thế Giới,2022,150x150,https://newshop.vn/combo-sach-tuong-phan-bo-4-...
2,Mèo Vũ Trụ,Mềm,https://newshop.vn/public/uploads/products/485...,Chạm - Hành Trình Cảm Xúc Của 12 Chòm Sao,184,99000,Nhà Sách AZ Việt Nam,Thế Giới,2022,130x180,https://newshop.vn/cham-hanh-trinh-cam-xuc-cua...
3,Manh A Công Tử,Mềm,https://newshop.vn/public/uploads/products/485...,Môn Đồ - Sư Phụ Giả - Tập 7,224,129000,Nhà Sách AZ Việt Nam,Thế Giới,2022,145x205,https://newshop.vn/mon-do-su-phu-gia-tap-7.htm...
4,Phạm Khôi Nguyên,Mềm,https://newshop.vn/public/uploads/products/485...,Bubu Và Titi - Hành Trình Học Hỏi Từ Thử Thách,52,88000,Nhà Xuất Bản Phụ Nữ,Phụ Nữ Việt Nam,2022,250x220,https://newshop.vn/bubu-va-titi-hanh-trinh-hoc...
...,...,...,...,...,...,...,...,...,...,...,...
45009,HT Thích Minh Thiền,Bìa mềm,No image,Tham thiền,302,189.000,Thái Hà Books,Tiếp tục,2020.0,(cm),https://book365.vn/sach/411073_tham-thien.html
45010,TS. Đặng Thị Việt Đức,Bìa mềm,No image,Quản trị tri thức trong Doanh nghiệp - Thời hạ...,302,11962.5,NXB Thông tin và Truyền thông,Thông tin và Truyền thông,2017.0,(cm),https://book365.vn/sach/416559_quan-tri-tri-th...
45011,Phòng Thương mại quốc tế ICC,Bìa mềm,No image,Bộ tập quán quốc tế về L/C - Các văn bản có hi...,302,9570,NXB Thông tin và Truyền thông,Thông tin và Truyền thông,2016.0,(cm),https://book365.vn/sach/416593_bo-tap-quan-quo...
45012,Lê Thị Thu Hà,Bìa mềm,No image,Bảo hộ chỉ dẫn địa lý của Việt Nam trong điều ...,302,18183,NXB Thông tin và Truyền thông,Thông tin và Truyền thông,2017.0,(cm),https://book365.vn/sach/416497_bao-ho-chi-dan-...
45013,TS. Đặng Thị Việt Đức,Bìa mềm,No image,Lý thuyết tài chính tiền tệ - Thời hạn: 12 tháng,302,16747.5,NXB Thông tin và Truyền thông,Thông tin và Truyền thông,2017.0,(cm),https://book365.vn/sach/416413_ly-thuyet-tai-c...